#!/bin/bash
# Run detached container install scripts
#
# Examples:
#
# install          # Run install scripts for web and api
# install -s api   # Run installs in api only
# install -e prod  # Target production containers
#
source "$LITEFARM_CLI_DIR/text.sh"
env=$LITEFARM_DOCKER_DEFAULT_ENV
able_services=(web api)

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  "-s")
    services+=("$2") && shift 2;;
  esac
done

[[ -z "${services[@]}" ]] && services=("${able_services[@]}")

for service in "${services[@]}"; do
  [[ $service != ${services[0]} ]] && echo
  title "Installing $service"
  lfcli sh -e $env -s $service -d install
done
