#!/bin/bash
# Show container logs
# Note that when containers are started idle, eg when using docker/dev. 
# The log will only show "Started idle".
# Relevant logs will instead be shown directly in the foreground process.
#
# Examples:
#
# docker/logs          # follow logs of web
# docker/logs -s api   # follow logs of api
# docker/logs -e prod  # Target production containers
#
docker="$(dirname "$0")"

env=$LITEFARM_DOCKER_DEFAULT_ENV
service=$LITEFARM_DOCKER_DEFAULT_SERVICE
follow=true

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  "-s")
    service="$2" && shift 2;;
  "+f")
    follow=false && shift;;
  esac
done

cmd=(docker logs)
$follow && cmd+=(-f)
cmd+=(litefarm-$service)

"${cmd[@]}"
