#!/bin/bash
# Migrate db
#
# Examples:
#
# migrate          # Run db migrations
# migrate -e prod  # Target production containers
env=$LITEFARM_DOCKER_DEFAULT_ENV
able_services=(api)

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  esac
done

for service in "${able_services[@]}"; do
  [[ $service != ${able_services[0]} ]] && echo
  lfcli sh -e $env -s $service -d migrate
done
