#!/bin/bash
# Precompile assets, mostly for production
#
# Examples:
#
# precompile          # Precompile assets for web
# precompile -e prod  # Target production containers
#
source "$LITEFARM_CLI_DIR/text.sh"
docker="$LITEFARM_DOCKER_CLI_DIR"
env=$LITEFARM_DOCKER_DEFAULT_ENV
able_services=(web)

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  esac
done

for service in "${able_services[@]}"; do
  [[ $service != ${able_services[0]} ]] && echo
  title "Precompiling $service"
  "$docker/sh" -e $env -s $service -d build
done
