#!/bin/bash
# Precompile assets, mostly for production
#
# Examples:
#
# docker/precompile          # Precompile assets for web
# docker/precompile -e prod  # Target production containers
#
docker="$LITEFARM_DOCKER_CLI_DIR"
env=$LITEFARM_DOCKER_DEFAULT_ENV
build_able_services=(web)

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  esac
done

for service in "${build_able_services[@]}"; do
  echo -e "Building $service\n"
  "$docker/sh" -e $env -s $service -d build
done
