#!/bin/bash
# Remove containers, safe as data is persisted through system volumes
# Note that containers have to be stopped first, docker/stop
#
# Examples:
#
# docker/rm               # Rm all containers
# docker/rm -s api -s db  # Rm api and db container
# docker/rm -e prod       # Target production containers
#
docker="$LITEFARM_DOCKER_CLI_DIR"
env=$LITEFARM_DOCKER_DEFAULT_ENV

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  "-s")
    services+=("$2") && shift 2;;
  "-f")
    rm_flags+=(-f)
  esac
done

"$docker/compose" -e $env -a rm "${rm_flags[@]}" "${services[@]}"
