#!/bin/bash
# Enter container shell or send shell command to container
#
# Examples:
#
# sh             # Enter bash shell in development web container:
# sh ls          # Run command directly
# sh -s api ls   # Run command in api container
# sh help        # Show custom web container commands
# sh -s api help # Show custom api container commands
# sh -d ls       # Run command in a detached container
# sh -e prod     # Target production containers
#
# See .bashrc files for relevant commands to run
#
env=$LITEFARM_DOCKER_DEFAULT_ENV
service=$LITEFARM_DOCKER_DEFAULT_SERVICE
detached=false
fallback=false

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  "-s")
    service=$2 && shift 2;;
  "-d")
    detached=true && shift;;
  "-b") # fallback to container shell after command exit
    fallback=true && shift;;
  esac
done

$detached && cmd=(run --rm) || cmd=(exec)
cmd+=(-it $service /bin/bash)

if [[ -n "$*" ]]; then 
  $fallback && cmd+=(-ci "$*; exec bash") || cmd+=(-ci "$*")
fi

lfcli compose -e $env -a "${cmd[@]}"
