#!/bin/bash
# Stop containers
#
# Examples:
#
# docker/stop               # Stop all containers
# docker/stop -s api -s db  # Stop api and db service
# docker/stop -e prod       # Target production containers
#
docker="$LITEFARM_DOCKER_CLI_DIR"
env=$LITEFARM_DOCKER_DEFAULT_ENV

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  "-s")
    services+=("$2") && shift 2;;
  esac
done

"$docker/compose" -e $env -a stop "${services[@]}"
