#!/bin/bash
# Stop containers
#
# Examples:
#
# stop               # Stop all containers
# stop -s api -s db  # Stop api and db service
# stop -e prod       # Target production containers
#
env=$LITEFARM_DOCKER_DEFAULT_ENV

for arg in "$@"; do
  case $arg in
  "-e")
    env=$2 && shift 2;;
  "-s")
    services+=("$2") && shift 2;;
  esac
done

lfcli compose -e $env -a stop "${services[@]}"
