#!/bin/bash
#####
# NAME
#   compose - run project compose command
#
# SYNOPSIS
#   compose [COMMAND...]
#
# COMMANDS
#   Commands are appended to project base compose command
#
# CONFIG
#   $LITEFARM_DOCKER_ENV 
#     Determines the base docker-compose file  
#   $LITEFARM_DOCKER_START_ADMINER 
#     Determines if adminer db manager will be included in the project
#
# EXAMPLES
#   compose         # Print base compose command 
#   compose ps      # List running services in compose project
#   compose config  # Show compose project config
#
# SEE ALSO
#   docker-compose --help
#####
user_cmd=("$@")
repo="$LITEFARM_REPO_ROOT"
cmd=(docker-compose --env-file "$repo/packages/api/.env" -f "$repo/docker-compose.$LITEFARM_DOCKER_ENV.yml")
$LITEFARM_DOCKER_START_ADMINER && cmd+=(-f "$repo/docker-compose.adminer.yml")

if [ -z "${user_cmd[*]}" ]; then
  # Just output base compose cmd if no user cmd provided
  echo "${cmd[*]}" && exit
else
  # Run compose cmd
  cmd+=("${user_cmd[@]}")
  lflog_cmd "${cmd[@]}"
  "${cmd[@]}"
fi
