#!/bin/bash
# These commands can be overwritten by developers by changing the 
# LITEFARM_CLI_COMMANDS_PATH to point to another file that follows the same syntax style
# See config.sh for info on config variables
#
# Any new case line that is followed by a comment ' #'
# will be added to the autogenerated help documentation
cmd=$1 && shift;
repo="$LITEFARM_REPO_PATH"
docker="$LITEFARM_DOCKER_CLI_DIR"

case $cmd in
  web) # Start developing webapp
    "$docker/dev" -s web "$@";;
  api) # Start developing api
    "$docker/dev" -s api "$@";;
  webpart) # Start dev web, leave api idle for faster dev startup in second terminal
    # When you know you want to dev both web and api in separate terminals, 
    # this if faster as avoids having to recreate api container
    "$docker/dev" -s web -i api "$@";;
  webl) # Follow web logs when not in dev mode
    "$docker/logs" -s web;;
  apil) # Follow api logs when not in dev mode
    "$docker/logs" -s api;;
  *)
    return 1
esac


